Update create-po.component.ts
ERROR in src/app/purchase-order/create-po/create-po.component.ts:124:49 - error TS2339: Property 'target' does not exist on type 'NavigationExtras'.

124       this.router.getCurrentNavigation().extras.target